
version = "1"


[HELLOA]
description = "hello"


[HELLO]
description = "hello"
value = "asdf"

[ANOTHER]
description = "Some description"
default = "yoooooo"

[TESTING]
description = "Some description"
optional = true

[TESTINGANOTHER]
description = "Some description"
optional = true
