
version = "1"





[C]
description = "something"
value = "{{ B }}fromC"



[E]
description = "something"
value = "fromD {{D}}"





[H]
description = "something"
value = "fromD {{G}}"

[O]
description = "something"
value = "fromD {{G}}"

[I]
description = "something"
value = "fromD {{H}}"



[K]
description = "something"
value = "fromD {{J}}"

[L]
description = "something"
value = "fromD {{K}}"

[M]
description = "something"
value = "fromD {{L  }} "





[HELLOA]
description = "hello"
value = "yay"

[qwer]
description = "hello"
value = "{{HELLOA}}"

[qwerT]
description = "hello"
value = "{{HELLOA}}"

[qwerTYG]
description = "hello"
value = "{{HELLOA}}"

[qwerTYH]
description = "hello"
value = "{{HELLOA}}"

[qwerTYI]
description = "hello"
value = "{{HELLOA}}"

[qwerTYJ]
description = "hello"
value = "{{HELLOA}}"

[ANOTHER_ROOT]
description = "hello"
value = "asdfyo"

[YET_ANOTHER_ROOT]
description = "hello"
default = "{{A_ROOT}}"

[ANOTHER]
description = "Some description"
value = "'{{ YET_ANOTHER_ROOT    }}'   ok  +{{ANOTHER_ROOT }}+ hello <{{    TESTING }}>    ummmm hello???"

[J]
description = "something"
value = "fromD {{I}}"

[OHMYGOD]
description = "Some description"
value = "'{{ ANOTHER    }} ++ "

[ABC]
description = "Some description"
value = "'{{ ANOTHER    }} ++ {{ OHMYGOD }} "


[TESTING]
description = "Some description"
value = "true"

[G]
description = "something"
value = "fromD {{F}}"

[B]
description = "something"
value = "{{ A }}fromB"

[TESTINGANOTHER]
description = "Some description"
optional = true

[A]
description = "something"
value = "fromA "

[F]
description = "something"
value = "fromD {{E}}"

[D]
description = "something"
value = "fromD {{C}}"


[A_ROOT]
description = "hello"
value = "asdf"
