
version = "1"

[A]
description = "something"
value = "fromA"

[B]
description = "something"
value = "{{ A }}fromB"

[C]
description = "something"
value = "{{ B }}fromC"

[D]
description = "something"
value = "fromD {{C}}"



[HELLOA]
description = "hello"


[A_ROOT]
description = "hello"
value = "asdf"

[ANOTHER_ROOT]
description = "hello"
value = "asdfyo"

[YET_ANOTHER_ROOT]
description = "hello"
default = "{{A_ROOT}}"

[ANOTHER]
description = "Some description"
value = "'{{ YET_ANOTHER_ROOT    }}'   ok  +{{ANOTHER_ROOT }}+ hello <{{    TESTING }}>    ummmm hello???"



[OHMYGOD]
description = "Some description"
value = "'{{ ANOTHER    }} ++ {{ OHMY }} "

[ABC]
description = "Some description"
value = "'{{ ANOTHER    }} ++ {{ OHMYGOD }} "


[TESTING]
description = "Some description"
value = "true"

[TESTINGANOTHER]
description = "Some description"
optional = true
