version = "1"


[A]
description = "variable A"
value = "{{ NOT HERE }}"

[B]
description = "variable B"
value = "{{ C }}"

[C]
description = "variable C"
default = "some_default"

[D]
description = "variable D"
optional = true
