version = "2"


[A]
description = "variable A"
value = "{{ }}"

[B]
description = "variable B"
value = "some_default"

[C]
description = "variable C"
default = "some_default"

[D]
description = "variable D"
optional = true
