version = "1"


[A]
description = "variable A"
value = "{{ B }}"

[B]
description = "variable B"
value = "{{ A }}"

[C]
description = "variable C"
default = "some_default"

[D]
description = "variable D"
optional = true
