version = "1"


[A]
description = "asdf"
extra = "not allowed"

[B]
description = "variable B"
value = "some_value"

[C]
description = "variable C"
default = "some_default"

[D]
description = "variable D"
optional = "true"
